### PR TITLE
TypeScript dependency is required

### PR DESCRIPTION
**Pull request by j-a-m-l**
```
...
> ng test

14 02 2018 10:18:18.181:ERROR [config]: Error in config file!
 Error: Could not find local "typescript" package.The "@ngtools/webpack" package requires a local "typescript@^2.0.2" package to be installed.Error: Cannot find module 'typescript'
    at Object.<anonymous> (/user/code/node_modules/@ngtools/webpack/src/index.js:18:11)
...
```

### CODE REVIEW

**Comment by lathonez** [comment]
You sure about this? Typescript comes packaged with the ionic starter

**Comment by j-a-m-l** [comment]
It's weird, and I don't know the real cause, but after `npm install typescript` everything worked fine.

**Comment by lathonez** [comment]
ok I'll take a look at it sometime

**Comment by lathonez** [comment]
Tried with a fresh ionic starter and couldn't replicate this.

**Pull request closed without merging**
